[env:waveshare_7inch_s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; These help identify the chip and memory layout correctly
board_build.mcu = esp32s3
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = qio
board_upload.flash_size = 16MB

monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM
    ; Force the use of the native USB for Serial
    -D ARDUINO_USB_SERIAL=1 
    -D CORE_DEBUG_LEVEL=5
	-D ESP_PANEL_BOARD_WAVESHARE_ESP32_S3_LCD_7
    -D ESP_PANEL_USE_WAVESHARE_ESP32_S3_LCD_7
	-I src/ ; Look for lv_conf.h in the src folder
lib_deps =
 lvgl@^8.4.0